-- MySQL Script generated by MySQL Workbench
-- Mon Jul 20 14:30:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema twitter_loader
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `twitter_loader` ;

-- -----------------------------------------------------
-- Schema twitter_loader
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twitter_loader` DEFAULT CHARACTER SET utf8mb4 ;
USE `twitter_loader` ;

-- -----------------------------------------------------
-- Table `twitter_loader`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`user` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`user` (
  `id` BIGINT(20) NOT NULL,
  `screen_name` VARCHAR(22) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `name` TINYTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL,
  `profile_image_url` TEXT NULL DEFAULT NULL,
  `location` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `url` TEXT NULL DEFAULT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `created` DATETIME NOT NULL,
  `followers_count` INT(10) UNSIGNED NULL DEFAULT 0,
  `friends_count` INT(10) UNSIGNED NULL DEFAULT 0,
  `statuses_count` INT(10) UNSIGNED NULL DEFAULT 0,
  `time_zone` VARCHAR(50) NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lang` CHAR(5) NULL,
  `utc_ofset` MEDIUMINT(6) NULL DEFAULT 0,
  `verified` TINYINT(1) UNSIGNED NOT NULL,
  `inserted` DATETIME NOT NULL,
  `status_geo_lat` DECIMAL(10,5) NULL DEFAULT NULL,
  `status_geo_long` DECIMAL(10,5) NULL DEFAULT NULL,
  `status_country` VARCHAR(200) NULL,
  `status_country_code` VARCHAR(5) NULL,
  `suspended` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `url_entity` TEXT NULL,
  `contributor` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `translator` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `default_profile` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `default_profile_image` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `show_all_inline_media` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `geo_enabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `protected_user` TINYINT(1) UNSIGNED NOT NULL,
  `email` VARCHAR(254) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `favourites_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `access_level` INT UNSIGNED NOT NULL DEFAULT 0,
  `listed_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `original_profile_image_url` TEXT NULL,
  `bigger_profile_image_url_https` TEXT NULL,
  `bigger_profile_image_url` TEXT NULL,
  `original_profile_image_url_https` TEXT NULL,
  `profile_banner_url` TEXT NULL,
  `profile_background_image_url` TEXT NULL,
  `profile_text_color` CHAR(7) NULL,
  `profile_link_color` CHAR(7) NULL,
  `profile_sidebar_fill_color` CHAR(7) NULL,
  `profile_sidebar_border_color` CHAR(7) NULL,
  `profile_background_color` CHAR(7) NULL,
  `parsed` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `withheld_in_countries` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `screen_name` (`screen_name`(20) ASC),
  FULLTEXT INDEX `description` (`description`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`tweet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`tweet` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`tweet` (
  `id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `text` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `annotated_text` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL,
  `created` DATETIME NOT NULL,
  `geo_lat` DECIMAL(10,5) NULL DEFAULT NULL,
  `geo_long` DECIMAL(10,5) NULL DEFAULT NULL,
  `retweeted` TINYINT(1) UNSIGNED NOT NULL,
  `retweet_count` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `favourite` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `favourite_count` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `lang` VARCHAR(200) NOT NULL,
  `country` VARCHAR(200) NULL,
  `country_code` VARCHAR(3) NULL,
  `possibly_sensitive` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NOT NULL,
  `length` INT NOT NULL COMMENT 'Length of the text',
  `in_reply_to_status_id` BIGINT(20) NOT NULL DEFAULT 0,
  `in_reply_to_screen_name` VARCHAR(20) NULL,
  `contributors` TEXT NULL,
  `source` TEXT NULL,
  `has_contributors` TINYINT(1) NOT NULL DEFAULT 0,
  `has_media` TINYINT(1) NOT NULL DEFAULT 0,
  `in_reply_to_user_id` BIGINT(20) NULL DEFAULT 0,
  `withheld_in_countries` TEXT NULL,
  `parsed` TINYINT(1) NULL DEFAULT 0,
  `mentions_count` INT NULL DEFAULT 0,
  `current_user_retweet_id` BIGINT(20) NULL DEFAULT 0,
  `truncated` TINYINT(1) NOT NULL DEFAULT 0,
  `access_level` INT(11) NOT NULL DEFAULT 0,
  `hashtag_count` INT(11) NOT NULL DEFAULT 0,
  `media_count` INT(11) NOT NULL DEFAULT 0,
  `url_count` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  FULLTEXT INDEX `tweet_text` (`text`),
  INDEX `fk_tweet_user1_idx` (`user_id` ASC),
  INDEX `created` (`created` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`tweet_cache`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`tweet_cache` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`tweet_cache` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tweet_id` BIGINT(20) NOT NULL,
  `cache_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `serialized_tweet` LONGBLOB NOT NULL,
  INDEX `cache_date` (`cache_date` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tweet_id_UNIQUE` (`tweet_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `twitter_loader`.`tweet_mention`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`tweet_mention` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`tweet_mention` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tweet_id` BIGINT(20) NOT NULL,
  `source_user_id` BIGINT(20) NOT NULL,
  `target_user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tweet_mention_user1_idx` (`source_user_id` ASC),
  INDEX `fk_tweet_mention_user2_idx` (`target_user_id` ASC),
  INDEX `fk_tweet_mention_tweet1_idx` (`tweet_id` ASC),
  UNIQUE INDEX `unique_mention` (`tweet_id` ASC, `source_user_id` ASC, `target_user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`hashtag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`hashtag` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`hashtag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(300) NOT NULL COMMENT 'Same at max tweet size!!!',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_UNIQUE` (`tag` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`url`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`url` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`url` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(2000) NOT NULL,
  `expanded_url` VARCHAR(2000) NOT NULL,
  `hash` VARCHAR(255) NOT NULL,
  `error` TINYINT(1) NOT NULL DEFAULT 0,
  `parsed` TINYINT(1) NOT NULL DEFAULT 0,
  `resolved` TEXT NULL,
  `host` VARCHAR(255) NULL,
  `title` VARCHAR(255) NULL,
  `content` LONGTEXT NULL,
  `keywords` VARCHAR(255) NULL,
  `html` LONGTEXT NULL,
  `language` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC),
  INDEX `parsed` (`parsed` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`query`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`query` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`query` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `query` VARCHAR(2000) NOT NULL,
  `type` ENUM('QUERY', 'USER', 'STREAM', 'TIMELINE', 'TREND') NOT NULL COMMENT 'QUERY: search by an input query\nUSER: search an input user\nSTREAM: search an stream of tweets\nTIMELINE: search the timeline of an input user\nTREND: search trend tweets',
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `launched_times` BIGINT(20) NULL DEFAULT 0,
  `exception` VARCHAR(2000) NULL,
  `max_id` BIGINT(20) NULL DEFAULT 0,
  `since_id` BIGINT(20) NULL DEFAULT 0,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1 is enabled\n0 is disabled',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`tweet_hashtag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`tweet_hashtag` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`tweet_hashtag` (
  `tweet_id` BIGINT(20) NOT NULL,
  `hashtag_id` INT NOT NULL,
  PRIMARY KEY (`hashtag_id`, `tweet_id`),
  INDEX `fk_tweet_has_hashtag_hashtag1_idx` (`hashtag_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`tweet_url`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`tweet_url` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`tweet_url` (
  `tweet_id` BIGINT(20) NOT NULL,
  `url_id` INT NOT NULL,
  PRIMARY KEY (`url_id`, `tweet_id`),
  INDEX `fk_tweet_has_url_url1_idx` (`url_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`user_cache`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`user_cache` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`user_cache` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `cache_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `serialized_user` LONGBLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  INDEX `cache_date` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`tweet_retweet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`tweet_retweet` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`tweet_retweet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source_tweet_id` BIGINT(20) NOT NULL COMMENT 'The ID of the retweet',
  `original_tweet_id` BIGINT(20) NOT NULL COMMENT 'The ID of the original tweet that was retweeted',
  `source_user_id` BIGINT(20) NOT NULL COMMENT 'Person who starts the retweet',
  `target_user_id` BIGINT(20) NOT NULL COMMENT 'Person who receives the retweet',
  PRIMARY KEY (`id`),
  INDEX `fk_tweet_retweet_user1_idx` (`source_user_id` ASC),
  INDEX `fk_tweet_retweet_user2_idx` (`target_user_id` ASC),
  INDEX `fk_tweet_retweet_tweet1_idx` (`original_tweet_id` ASC),
  UNIQUE INDEX `unique_retweet` (`target_user_id` ASC, `source_user_id` ASC, `original_tweet_id` ASC),
  INDEX `fk_tweet_retweet_tweet1_idx1` (`source_tweet_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`user_knowledge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`user_knowledge` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`user_knowledge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `sex` CHAR(1) NULL DEFAULT 'U' COMMENT 'Female (F) or Male (M)',
  `years` INT NULL,
  `classification` VARCHAR(254) NULL,
  `role` VARCHAR(254) NULL,
  `city` VARCHAR(254) NULL,
  `country_code` VARCHAR(45) NULL,
  `country` VARCHAR(254) NULL,
  `continent` VARCHAR(254) NULL,
  `is_influencer` TINYINT(1) NULL,
  `image_blob` MEDIUMBLOB NULL,
  `curated` TINYINT(1) NOT NULL DEFAULT 0,
  `parsed` TINYINT(1) NOT NULL DEFAULT 0,
  `geo_lat` DECIMAL(10,5) NULL DEFAULT NULL,
  `geo_long` DECIMAL(10,5) NULL DEFAULT NULL,
  `detected_gender_by` VARCHAR(254) NULL,
  `influencer_measure` DECIMAL NULL,
  `ftf_ratio` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_knowledgement_user1_idx` (`user_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  INDEX `role` (`role` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`tweet_knowledge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`tweet_knowledge` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`tweet_knowledge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tweet_id` BIGINT(20) NOT NULL,
  `polarity` VARCHAR(45) NULL,
  `subjectivity` VARCHAR(45) NULL,
  `curated` TINYINT(1) NOT NULL DEFAULT 0,
  `parsed` TINYINT(1) NOT NULL DEFAULT 0,
  `total_tokens` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Preprocessed stop word and numbers',
  `self_repeated_count` INT NOT NULL DEFAULT 0,
  `other_repeated_count` INT NOT NULL DEFAULT 0,
  `source_chain` TINYINT(1) NOT NULL DEFAULT 0,
  `source_tweet_id` BIGINT(20) NOT NULL DEFAULT 0,
  `thematic` VARCHAR(45) NULL,
  `checked_duplicity` TINYINT(1) NOT NULL DEFAULT 0,
  `short_message` TINYINT(1) NOT NULL DEFAULT 0,
  `text_annotated_replace` VARCHAR(240) NOT NULL,
  `annotated_html` VARCHAR(240) NOT NULL,
  `sentiment_compound` FLOAT NULL,
  `word_count` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fk_tweet_knowledgement_tweet1_idx` (`tweet_id` ASC),
  INDEX `parsed` (`parsed` ASC),
  INDEX `checked_duplicity` (`checked_duplicity` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`media` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`media` (
  `id` BIGINT(20) NOT NULL,
  `ext_alt_text` TEXT NULL,
  `media_url` TEXT NOT NULL,
  `media_url_https` TEXT NOT NULL,
  `type` TEXT NOT NULL,
  `video_duration_millis` INT NOT NULL DEFAULT 0,
  `hash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`tweet_quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`tweet_quote` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`tweet_quote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source_tweet_id` BIGINT(20) NOT NULL COMMENT 'The ID of the tweet that make the quote',
  `quoted_tweet_id` BIGINT(20) NOT NULL COMMENT 'The ID of the tweet that was quoted',
  `source_user_id` BIGINT(20) NOT NULL COMMENT 'Person who makes the quote',
  `quoted_user_id` BIGINT(20) NOT NULL COMMENT 'Person who receives the quote',
  PRIMARY KEY (`id`),
  INDEX `fk_tweet_retweet_user1_idx` (`source_user_id` ASC),
  INDEX `fk_tweet_retweet_user2_idx` (`quoted_user_id` ASC),
  INDEX `fk_tweet_quote_tweet1_idx` (`quoted_tweet_id` ASC),
  UNIQUE INDEX `unique_quote` (`quoted_user_id` ASC, `source_user_id` ASC, `quoted_tweet_id` ASC),
  INDEX `fk_tweet_quote_tweet2_idx` (`source_tweet_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`tweet_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`tweet_media` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`tweet_media` (
  `tweet_id` BIGINT(20) NOT NULL,
  `media_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`tweet_id`, `media_id`),
  INDEX `fk_tweet_media_media1_idx` (`media_id` ASC),
  INDEX `fk_tweet_media_tweet1_idx` (`tweet_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`query_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`query_user` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`query_user` (
  `query_id` INT NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`query_id`, `user_id`),
  INDEX `fk_query_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_query_has_user_query1_idx` (`query_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_loader`.`query_tweet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_loader`.`query_tweet` ;

CREATE TABLE IF NOT EXISTS `twitter_loader`.`query_tweet` (
  `query_id` INT NOT NULL,
  `tweet_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`query_id`, `tweet_id`),
  INDEX `fk_query_has_tweet_tweet1_idx` (`tweet_id` ASC),
  INDEX `fk_query_has_tweet_query1_idx` (`query_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `twitter_loader`.`query`
-- -----------------------------------------------------
START TRANSACTION;
USE `twitter_loader`;
INSERT INTO `twitter_loader`.`query` (`id`, `query`, `type`, `created`, `modified`, `launched_times`, `exception`, `max_id`, `since_id`, `enabled`) VALUES (1, '35701409', 'TIMELINE', '2020-07-08 13:10:02.047', '2020-07-08 13:10:02.047', 0, NULL, 0, 0, 1);
INSERT INTO `twitter_loader`.`query` (`id`, `query`, `type`, `created`, `modified`, `launched_times`, `exception`, `max_id`, `since_id`, `enabled`) VALUES (2, 'coronavirus', 'QUERY', '2020-07-08 13:10:02.047', '2020-07-08 13:10:02.047', 0, NULL, 0, 0, 1);

COMMIT;

